### ISSUE TITLE
[node_experimental] TypeError: testEnabled is not a function

### ISSUE THREAD

**Issue by silverpill** [rscarson/rustyscript#330]
**Describe the bug**

`Server.listen` fails with an error: `TypeError: testEnabled is not a function`

**To Reproduce**

```rust
use rustyscript::{Error, Module, Runtime};

fn main() -> Result<(), Error> {
    let module = Module::new(
        "test.js",
        r#"
        import * as net from "node:net"
        const server = net.createServer()
        server.listen(8124, () => {
            console.log("server bound")
        })
        "#
    );
    let () = Runtime::execute_module(
        &module, vec![],
        Default::default(),
        &(),
    )?;
    Ok(())
}
```

**Expected behavior**

This JavaScript snippet works in Deno.

**Comment by rscarson** [comment]
Seems I missed a function somewhere in my boostrapping!

**Comment by rscarson** [comment]
Fixed in master, will leave this open this the next version publishes.

**Comment by silverpill** [comment]
Thank you!
`TypeError` doesn't appear when running rustyscript from master, but the code from the example still doesn't work as it does in Deno.

The "server bound" message is never printed, and the server doesn't appear to be listening. Edited example (added await to prevent program from terminating immediately):

```rust
use rustyscript::{Error, Module, Runtime};

fn main() -> Result<(), Error> {
    let module = Module::new(
        "test.js",
        r#"
        import * as net from "node:net"
        const server = net.createServer()
        server.listen(8124, () => {
            console.log("server bound")
        })

        export default async function test() {
            await new Promise((resolve, reject) => {
                server.on("listening", resolve)
                server.on("error", reject)
            })
        }
        "#
    );
    let mut runtime = Runtime::new(Default::default())?;
    let handle = runtime.load_module(&module)?;
    let () = runtime.call_entrypoint(
        &handle,
        &(),
    )?;
    Ok(())
}
```

**Comment by rscarson** [comment]
Fixed in release 0.12.0
